datasource:
    name: mysql
    continue-on-error: false
    max-active: 100
    max-idle: 60
    min-idle: 30
    initial-size: 50
    validation-query: select 1
    test-on-borrow: true
    test-on-return: true
    time-between-eviction-runs-millis: 10000
    min-evictable-idle-time-millis: 60000
    max-wait: 10000
    jmx-enabled: false
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: "root"
server:
    port: 8080
#    tomcat:
#        uriEncoding: UTF-8
#        maxHttpHeaderSize: 16384
#        compression: on
#        compressableMimeTypes: text/html,text/plain,application/json
#        max-threads: 3000


myProps: #自定义的属性和值
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps:
    key1: value1
    key2: value2
